package com.exception;

public class Arrayoutofbound {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Data d=new Data();
		
		d.data1();
	}

}
class Data
{
	public void data1()
	{
		
		data2();
		System.out.println("data2length"+("data1".length()));
	}
	public void data2()
	{
		data();
		System.out.println("data3length"+("data2".length()));
	}
	public void data()
	{
		try
		{
			int[] a= {1,2};
			int number=a[4];
		}
		catch(ArrayIndexOutOfBoundsException ae)
		{
			System.out.println("ArrayIndexoutofBoundException is:"+ae);
		}
		catch(NullPointerException e1)
		{
			System.out.println("NullPointerException is:"+e1);

		}
		catch(Exception e)
		{
//			System.out.println("Exception is"+e);
			e.printStackTrace();
		}
	}
}
